name: "CAN-MQTT Connector"
version: "1.0.17"
slug: "can_mqtt_connector"
description: "Führt das Python-Skript und can-utils aus"
arch:
  - aarch64
  - amd64
  - armv7
startup: "application"
boot: "auto"
init: false
options: {}
schema: {}
map:
  - config:rw
host_time: true
devices:
  - "/dev/serial/by-id/usb-Openlight_Labs_CANable2_b158aa7_github.com_normaldotcom_canable2.git_206B336A5845-if00:/dev/serial/by-id/usb-Openlight_Labs_CANable2_b158aa7_github.com_normaldotcom_canable2.git_206B336A5845-if00"
host_network: true
