name: "CAN-MQTT Connector"
version: "1.0.0"
slug: "can_mqtt_connector"
description: "Führt das Python-Skript und can-utils aus"
arch:
  - aarch64
  - amd64
  - armv7
startup: "application"
boot: "auto"
init: false
options: {}
schema: {}
map:
  - config:rw
devices:
  - /dev/serial/by-id/usb-Openlight_Labs_CANable2_b158aa7_github.com_normaldotcom_canable2.git_209035805741-if00:/dev/ttyACM0

host_network: true
